
skillMetadata:
  sections:
    - name: Humor Settings
      fields:
        - name: humor_level
          type: number
          label: Humor setting (between 0-100)
          value: "60"
    - name: Baby Info
      fields:
        - name: baby_name
          type: text
          label: Baby's Name
          value: ""
        - name: gender
          type: select
          label: Gender
          options: Male|male;Female|female
          value: female
