
skillMetadata:
  sections:
    - name: Baby Info
      fields:
        - name: baby_name
          type: text
          label: Baby's Name
          value: ""
        - name: gender
          type: select
          label: Gender
          options: Male|male;Female|female
          value: female
